version: '3.8'

services:
  # 简化版后端服务 (Python HTTP服务器)
  simple-backend:
    build:
      context: .
      dockerfile: Dockerfile.python-backend
    container_name: pet-simple-backend-local
    restart: unless-stopped
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - pet-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 3s
      retries: 3

  # 前端服务 (Python HTTP服务器提供静态文件)
  frontend:
    build:
      context: ./pet-frontend
      dockerfile: Dockerfile.python-frontend
    container_name: pet-frontend-local
    restart: unless-stopped
    depends_on:
      - simple-backend
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - pet-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3001')"]
      interval: 30s
      timeout: 3s
      retries: 3

# 网络配置
networks:
  pet-network:
    driver: bridge